from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '1aa344def442'
down_revision: Union[str, Sequence[str], None] = '185fabe6c96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('section_id', sa.String(length=50), nullable=False))
    op.add_column('answer', sa.Column('auto_score', sa.Float(), nullable=True))
    op.add_column('answer', sa.Column('manual_score', sa.Float(), nullable=True))
    op.add_column('answer', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('answer', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index('idx_answer_section', 'answer', ['session_id', 'section_id'], unique=False)
    op.create_index(op.f('ix_answer_question_id'), 'answer', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_session_id'), 'answer', ['session_id'], unique=False)
    op.add_column('assessment_session', sa.Column('section_deadlines', sa.JSON(), nullable=True))
    op.add_column('assessment_session', sa.Column('completed_sections', sa.JSON(), nullable=True))
    op.add_column('assessment_session', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('assessment_session', sa.Column('device_fingerprint', sa.Text(), nullable=True))
    op.add_column('assessment_session', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('assessment_session', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('assessment_session', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('assessment_session', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED', name='sessionstatus'),
               existing_nullable=False)
    op.alter_column('assessment_session', 'cheating_risk',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CLEAN', 'MINOR', 'HIGH', name='cheatingrisk'),
               existing_nullable=True)
    op.alter_column('assessment_session', 'eligibility',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'AUTO_ELIGIBLE', 'AUTO_BLOCKED', 'MANAGER_OVERRIDDEN', name='eligibilitystatus'),
               existing_nullable=False)
    op.alter_column('assessment_session', 'overridden_by',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_assessment_session_candidate_id'), 'assessment_session', ['candidate_id'], unique=False)
    op.create_foreign_key(None, 'assessment_session', 'users', ['overridden_by'], ['id'])
    op.add_column('assessment_template', sa.Column('role', sa.String(length=200), nullable=False))
    op.add_column('assessment_template', sa.Column('job_role_id', sa.Integer(), nullable=False))
    op.add_column('assessment_template', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('assessment_template', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('assessment_template', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('assessment_template', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('assessment_template', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('assessment_template', 'sections_config',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.create_foreign_key(None, 'assessment_template', 'job_role_thresholds', ['job_role_id'], ['id'])
    op.create_foreign_key(None, 'assessment_template', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'assessment_template', 'users', ['created_by'], ['id'])
    op.drop_column('assessment_template', 'job_role')
    op.add_column('question_bank', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('question_bank', sa.Column('role', sa.String(length=200), nullable=True))
    op.add_column('question_bank', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('question_bank', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('question_bank', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('question_bank', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('question_bank', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MCQ', 'CODING', name='questiontype'),
               existing_nullable=False)
    op.alter_column('question_bank', 'correct_answer',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('question_bank', 'language',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PYTHON', 'JAVASCRIPT', 'JAVA', 'C', 'CPP', 'CSHARP', name='programminglanguage'),
               existing_nullable=False)
    op.alter_column('question_bank', 'difficulty',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               existing_nullable=True)
    op.create_foreign_key(None, 'question_bank', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'question_bank', 'users', ['updated_by'], ['id'])
    op.drop_column('question_bank', 'job_role')
    op.add_column('question_history', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('question_history', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('question_history', sa.Column('role', sa.String(length=200), nullable=True))
    op.add_column('question_history', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('question_history', sa.Column('public_test_cases', sa.JSON(), nullable=True))
    op.add_column('question_history', sa.Column('hidden_test_cases', sa.JSON(), nullable=True))
    op.alter_column('question_history', 'correct_answer',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('question_history', 'changed_by',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_question_history_question_id'), 'question_history', ['question_id'], unique=False)
    op.create_unique_constraint('uq_question_version', 'question_history', ['question_id', 'version'])
    op.create_foreign_key(None, 'question_history', 'users', ['changed_by'], ['id'])
    op.drop_column('question_history', 'job_role')
    op.add_column('session_question', sa.Column('section_id', sa.String(length=50), nullable=False))
    op.create_index('idx_session_question_section', 'session_question', ['session_id', 'section_id'], unique=False)
    op.create_index(op.f('ix_session_question_question_id'), 'session_question', ['question_id'], unique=False)
    op.create_index(op.f('ix_session_question_session_id'), 'session_question', ['session_id'], unique=False)
    op.add_column('template_history', sa.Column('role', sa.String(length=200), nullable=False))
    op.alter_column('template_history', 'sections_config',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('template_history', 'changed_by',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_template_history_template_id'), 'template_history', ['template_id'], unique=False)
    op.create_unique_constraint('uq_template_version', 'template_history', ['template_id', 'version'])
    op.create_foreign_key(None, 'template_history', 'users', ['changed_by'], ['id'])
    op.drop_column('template_history', 'job_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_history', sa.Column('job_role', sa.VARCHAR(length=200), nullable=False))
    op.drop_constraint(None, 'template_history', type_='foreignkey')
    op.drop_constraint('uq_template_version', 'template_history', type_='unique')
    op.drop_index(op.f('ix_template_history_template_id'), table_name='template_history')
    op.alter_column('template_history', 'changed_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('template_history', 'sections_config',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.drop_column('template_history', 'role')
    op.drop_index(op.f('ix_session_question_session_id'), table_name='session_question')
    op.drop_index(op.f('ix_session_question_question_id'), table_name='session_question')
    op.drop_index('idx_session_question_section', table_name='session_question')
    op.drop_column('session_question', 'section_id')
    op.add_column('question_history', sa.Column('job_role', sa.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'question_history', type_='foreignkey')
    op.drop_constraint('uq_question_version', 'question_history', type_='unique')
    op.drop_index(op.f('ix_question_history_question_id'), table_name='question_history')
    op.alter_column('question_history', 'changed_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('question_history', 'correct_answer',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('question_history', 'hidden_test_cases')
    op.drop_column('question_history', 'public_test_cases')
    op.drop_column('question_history', 'language')
    op.drop_column('question_history', 'role')
    op.drop_column('question_history', 'tags')
    op.drop_column('question_history', 'description')
    op.add_column('question_bank', sa.Column('job_role', sa.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'question_bank', type_='foreignkey')
    op.drop_constraint(None, 'question_bank', type_='foreignkey')
    op.alter_column('question_bank', 'difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('question_bank', 'language',
               existing_type=sa.Enum('PYTHON', 'JAVASCRIPT', 'JAVA', 'C', 'CPP', 'CSHARP', name='programminglanguage'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('question_bank', 'correct_answer',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('question_bank', 'type',
               existing_type=sa.Enum('MCQ', 'CODING', name='questiontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('question_bank', 'updated_at')
    op.drop_column('question_bank', 'created_at')
    op.drop_column('question_bank', 'updated_by')
    op.drop_column('question_bank', 'created_by')
    op.drop_column('question_bank', 'role')
    op.drop_column('question_bank', 'tags')
    op.add_column('assessment_template', sa.Column('job_role', sa.VARCHAR(length=200), nullable=False))
    op.drop_constraint(None, 'assessment_template', type_='foreignkey')
    op.drop_constraint(None, 'assessment_template', type_='foreignkey')
    op.drop_constraint(None, 'assessment_template', type_='foreignkey')
    op.alter_column('assessment_template', 'sections_config',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.drop_column('assessment_template', 'updated_at')
    op.drop_column('assessment_template', 'created_at')
    op.drop_column('assessment_template', 'updated_by')
    op.drop_column('assessment_template', 'created_by')
    op.drop_column('assessment_template', 'is_active')
    op.drop_column('assessment_template', 'job_role_id')
    op.drop_column('assessment_template', 'role')
    op.drop_constraint(None, 'assessment_session', type_='foreignkey')
    op.drop_index(op.f('ix_assessment_session_candidate_id'), table_name='assessment_session')
    op.alter_column('assessment_session', 'overridden_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('assessment_session', 'eligibility',
               existing_type=sa.Enum('PENDING', 'AUTO_ELIGIBLE', 'AUTO_BLOCKED', 'MANAGER_OVERRIDDEN', name='eligibilitystatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('assessment_session', 'cheating_risk',
               existing_type=sa.Enum('CLEAN', 'MINOR', 'HIGH', name='cheatingrisk'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('assessment_session', 'status',
               existing_type=sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED', name='sessionstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('assessment_session', 'updated_at')
    op.drop_column('assessment_session', 'created_at')
    op.drop_column('assessment_session', 'user_agent')
    op.drop_column('assessment_session', 'device_fingerprint')
    op.drop_column('assessment_session', 'ip_address')
    op.drop_column('assessment_session', 'completed_sections')
    op.drop_column('assessment_session', 'section_deadlines')
    op.drop_index(op.f('ix_answer_session_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_question_id'), table_name='answer')
    op.drop_index('idx_answer_section', table_name='answer')
    op.drop_column('answer', 'updated_at')
    op.drop_column('answer', 'created_at')
    op.drop_column('answer', 'manual_score')
    op.drop_column('answer', 'auto_score')
    op.drop_column('answer', 'section_id')
    # ### end Alembic commands ###
