from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '451d108ee9ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('job_role', sa.String(length=200), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('sections_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_template_id'), 'assessment_template', ['id'], unique=False)
    op.create_table('job_role_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_role_name', sa.String(length=255), nullable=False),
    sa.Column('ats_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_role_thresholds_id'), 'job_role_thresholds', ['id'], unique=False)
    op.create_index(op.f('ix_job_role_thresholds_job_role_name'), 'job_role_thresholds', ['job_role_name'], unique=True)
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('job_role', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_test_cases', sa.JSON(), nullable=True),
    sa.Column('hidden_test_cases', sa.JSON(), nullable=True),
    sa.Column('coding_reference', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_id'), 'question_bank', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'CANDIDATE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('api_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'api_audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_endpoint', 'api_audit_log', ['endpoint'], unique=False)
    op.create_index('idx_audit_user', 'api_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_audit_log_id'), 'api_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_api_audit_log_user_id'), 'api_audit_log', ['user_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('job_role_id', sa.Integer(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('shortlisted', sa.Boolean(), nullable=False),
    sa.Column('shortlisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_role_thresholds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=True)
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_code', 'otp', ['otp_code'], unique=False)
    op.create_index('idx_otp_expires', 'otp', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_id'), 'otp', ['id'], unique=False)
    op.create_index(op.f('ix_otp_user_id'), 'otp', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reset_token_expires', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('idx_reset_token_used', 'password_reset_tokens', ['used'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('question_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('job_role', sa.String(length=200), nullable=True),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_history_id'), 'question_history', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_token_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_token_revoked', 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('template_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('job_role', sa.String(length=200), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('sections_config', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_history_id'), 'template_history', ['id'], unique=False)
    op.create_table('assessment_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('allowed_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('integrity_score', sa.Float(), nullable=False),
    sa.Column('cheating_risk', sa.String(length=50), nullable=True),
    sa.Column('eligibility', sa.String(length=50), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.String(length=200), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_session_access_token'), 'assessment_session', ['access_token'], unique=True)
    op.create_index(op.f('ix_assessment_session_id'), 'assessment_session', ['id'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_data', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_session_answer')
    )
    op.create_index(op.f('ix_answer_id'), 'answer', ['id'], unique=False)
    op.create_table('proctor_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('MOBILE_DETECTED', 'MULTIPLE_FACE', 'NO_FACE', 'LOUD_VOICE', 'MULTIPLE_VOICE', 'LIP_SYNC_MISMATCH', 'TAB_SWITCH', 'COPY_PASTE', 'SCREEN_SHARE', 'FULLSCREEN_EXIT', 'DARK_ENVIRONMENT', name='proctoreventtype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='severitylevel'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('snapshot_url', sa.String(length=500), nullable=True),
    sa.Column('clip_url', sa.String(length=500), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proctor_event_id'), 'proctor_event', ['id'], unique=False)
    op.create_index(op.f('ix_proctor_event_session_id'), 'proctor_event', ['session_id'], unique=False)
    op.create_table('recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('quality_level', sa.String(length=20), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'chunk_index', name='uq_recording_session_chunk')
    )
    op.create_index('idx_recording_session', 'recording', ['session_id'], unique=False)
    op.create_index(op.f('ix_recording_id'), 'recording', ['id'], unique=False)
    op.create_index(op.f('ix_recording_session_id'), 'recording', ['session_id'], unique=False)
    op.create_table('reference_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('face_encoding', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ref_photo_candidate', 'reference_photo', ['candidate_id'], unique=False)
    op.create_index('idx_ref_photo_session', 'reference_photo', ['session_id'], unique=False)
    op.create_index(op.f('ix_reference_photo_candidate_id'), 'reference_photo', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_reference_photo_id'), 'reference_photo', ['id'], unique=False)
    op.create_index(op.f('ix_reference_photo_session_id'), 'reference_photo', ['session_id'], unique=False)
    op.create_table('session_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_session_question')
    )
    op.create_index(op.f('ix_session_question_id'), 'session_question', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_question_id'), table_name='session_question')
    op.drop_table('session_question')
    op.drop_index(op.f('ix_reference_photo_session_id'), table_name='reference_photo')
    op.drop_index(op.f('ix_reference_photo_id'), table_name='reference_photo')
    op.drop_index(op.f('ix_reference_photo_candidate_id'), table_name='reference_photo')
    op.drop_index('idx_ref_photo_session', table_name='reference_photo')
    op.drop_index('idx_ref_photo_candidate', table_name='reference_photo')
    op.drop_table('reference_photo')
    op.drop_index(op.f('ix_recording_session_id'), table_name='recording')
    op.drop_index(op.f('ix_recording_id'), table_name='recording')
    op.drop_index('idx_recording_session', table_name='recording')
    op.drop_table('recording')
    op.drop_index(op.f('ix_proctor_event_session_id'), table_name='proctor_event')
    op.drop_index(op.f('ix_proctor_event_id'), table_name='proctor_event')
    op.drop_table('proctor_event')
    op.drop_index(op.f('ix_answer_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_assessment_session_id'), table_name='assessment_session')
    op.drop_index(op.f('ix_assessment_session_access_token'), table_name='assessment_session')
    op.drop_table('assessment_session')
    op.drop_index(op.f('ix_template_history_id'), table_name='template_history')
    op.drop_table('template_history')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_revoked', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_question_history_id'), table_name='question_history')
    op.drop_table('question_history')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index('idx_reset_token_used', table_name='password_reset_tokens')
    op.drop_index('idx_reset_token_expires', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_otp_user_id'), table_name='otp')
    op.drop_index(op.f('ix_otp_id'), table_name='otp')
    op.drop_index('idx_otp_expires', table_name='otp')
    op.drop_index('idx_otp_code', table_name='otp')
    op.drop_table('otp')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_api_audit_log_user_id'), table_name='api_audit_log')
    op.drop_index(op.f('ix_api_audit_log_id'), table_name='api_audit_log')
    op.drop_index('idx_audit_user', table_name='api_audit_log')
    op.drop_index('idx_audit_endpoint', table_name='api_audit_log')
    op.drop_index('idx_audit_created', table_name='api_audit_log')
    op.drop_table('api_audit_log')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_question_bank_id'), table_name='question_bank')
    op.drop_table('question_bank')
    op.drop_index(op.f('ix_job_role_thresholds_job_role_name'), table_name='job_role_thresholds')
    op.drop_index(op.f('ix_job_role_thresholds_id'), table_name='job_role_thresholds')
    op.drop_table('job_role_thresholds')
    op.drop_index(op.f('ix_assessment_template_id'), table_name='assessment_template')
    op.drop_table('assessment_template')
    # ### end Alembic commands ###
